-- MySQL Script generated by MySQL Workbench
-- Thu Sep 14 16:38:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema practicas_intermedias
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `practicas_intermedias` ;

-- -----------------------------------------------------
-- Schema practicas_intermedias
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `practicas_intermedias` DEFAULT CHARACTER SET utf8 ;
USE `practicas_intermedias` ;

-- -----------------------------------------------------
-- Table `practicas_intermedias`.`course_student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `practicas_intermedias`.`course_student` ;

CREATE TABLE IF NOT EXISTS `practicas_intermedias`.`course_student` (
  `id_course_student` INT NOT NULL,
  `course_id` INT NOT NULL,
  `student_dpi` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`id_course_student`),
  INDEX `fk_course_student_courses1_idx` (`course_id` ASC) VISIBLE,
  INDEX `fk_course_student_users1_idx` (`student_dpi` ASC) VISIBLE,
  CONSTRAINT `fk_course_student_courses1`
    FOREIGN KEY (`course_id`)
    REFERENCES `practicas_intermedias`.`courses` (`id_course`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_student_users1`
    FOREIGN KEY (`student_dpi`)
    REFERENCES `practicas_intermedias`.`users` (`dpi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `practicas_intermedias`.`courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `practicas_intermedias`.`courses` ;

CREATE TABLE IF NOT EXISTS `practicas_intermedias`.`courses` (
  `id_course` INT NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `start_time` VARCHAR(10) NOT NULL,
  `end_time` VARCHAR(10) NOT NULL,
  `id_professor` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`id_course`),
  INDEX `fk_courses_users1_idx` (`id_professor` ASC) VISIBLE,
  CONSTRAINT `fk_courses_users1`
    FOREIGN KEY (`id_professor`)
    REFERENCES `practicas_intermedias`.`users` (`dpi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `practicas_intermedias`.`user_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `practicas_intermedias`.`user_type` ;

CREATE TABLE IF NOT EXISTS `practicas_intermedias`.`user_type` (
  `id_user_type` INT NOT NULL,
  `type` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_user_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `practicas_intermedias`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `practicas_intermedias`.`users` ;

CREATE TABLE IF NOT EXISTS `practicas_intermedias`.`users` (
  `dpi` VARCHAR(13) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `birth_date` DATE NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `phone` VARCHAR(11) NULL,
  `user` VARCHAR(20) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `user_type_id_user_type` INT NOT NULL,
  PRIMARY KEY (`dpi`),
  INDEX `fk_users_user_type_idx` (`user_type_id_user_type` ASC) VISIBLE,
  CONSTRAINT `fk_users_user_type`
    FOREIGN KEY (`user_type_id_user_type`)
    REFERENCES `practicas_intermedias`.`user_type` (`id_user_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
